services:
  app:
    command: ./venv/bin/python -B -u -m app.app
    volumes:
      - ./app:/app/app
  ssh:
    build:
      dockerfile_inline: |
        FROM alpine:3.20
        RUN <<EOF
        apk add --no-cache openssh-server
        ssh-keygen -A
        echo 'PermitRootLogin yes' >/etc/ssh/sshd_config.d/app.conf
        EOF
        CMD ["/usr/sbin/sshd","-D"]
    volumes:
      - ./cfg/id_ed25519.pub:/root/.ssh/authorized_keys
